# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod vendor
    - ./scripts/vendor-licenses -gen > NOTICE
builds:
  - id: ldap
    main: main.go
    binary: ldap
    goos:
      - darwin
      - freebsd
      - linux
      - windows
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files:
    - LICENSE
    - NOTICE
    - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: NetAuth
    name: ldap
